include .env

run-all:
	exec docker-compose -f ./docker-compose.yml up -d
	make run-auth

run-auth:
	export GOPATH=D:\Dev\Projects\gRPC_EncryptionService\AuthServer
	go build -o .\AuthServer\bin\go_build_AuthServer.exe AuthServer #gosetup
	D:\Dev\Projects\gRPC_EncryptionService\AuthServer\bin\go_build_AuthServer.exe
