info:
  contact: {}
paths:
  /:
    get:
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Main html page
      tags:
      - gui
  /AddUpdateStorageRecord:
    post:
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: Update or create storage on Encryption Server, through gRPC
      tags:
      - gui
  /DeleteRecord:
    post:
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: DeleteRecord by storage from Encryption Server, through gRPC
      tags:
      - gui
  /GetStorage:
    post:
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: Getting storage from Encryption Server, through gRPC
      tags:
      - gui
  /api/heartbeat:
    get:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      summary: Heartbeat metric
      tags:
      - Metrics
swagger: "2.0"
